name: Build Al-ML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.24.3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Build Al-ML
        run: ./tasks/dev run
      - name: Run primes
        run: ./src/samples/primes
